CREATE DATABASE IF NOT EXISTS `unity_rts`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `unity_rts`;

CREATE TABLE IF NOT EXISTS `rts_kv_store` (
  `name` VARCHAR(64) NOT NULL PRIMARY KEY,
  `data` JSON NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
